Bck 2 develop(Connection server with client)
VictorApopiy/C-_Practice_Notes_Keeper pull request #2
Opened 2022-06-14 10:17 UTC by KrayVlad

2022-06-14 18:52 UTC, Cardun requested changes
Please resolve messages that I left in commits, this PR doesn't have any changes stated

2022-06-27 10:57 UTC, KrayVlad commented
Resolved variable name

2022-06-27 10:57 UTC, Cardun approved these changes

2022-06-30 10:04 UTC, closed without merging

2022-06-30 10:05 UTC, Cardun commented
Closing, because everything was moved to BCK-6 branch